from copy import deepcopy
from typing import Any

from app.schemas.migration import MigrationJobCreate, MigrationTemplateRead


_JDE_BASE_CONFIG: dict[str, Any] = {
    "migration_strategy": "external_ora2pg",
    "notes": "Run ora2pg or another external bulk loader outside FastAPI, then record the run and validate the PostgreSQL staging target in MDP.",
}


_TEMPLATES: dict[str, MigrationTemplateRead] = {
    "jde_supplier_master": MigrationTemplateRead(
        template_key="jde_supplier_master",
        display_name="JDE Supplier Master",
        description="Tracks external ora2pg migration for JDE supplier master data.",
        source_system="JDE Oracle",
        source_type="oracle",
        migration_tool="ora2pg",
        source_schema_suggestion="PRODDTA",
        source_table="F0101",
        related_source_tables=["F0401"],
        target_schema="mdp_staging",
        target_table="stg_jde_supplier",
        primary_key_columns=["supplier_code"],
        load_mode="external_bulk",
        initial_load_strategy="external_defined",
        incremental_strategy="greater_than_last_watermark",
        watermark_column="updated_at",
        watermark_column_type="datetime",
        lookback_window_days=1,
        validation_level="key_integrity",
        config={
            **_JDE_BASE_CONFIG,
            "ora2pg_project": "jde_supplier_master",
            "jde_tables": ["F0101", "F0401"],
            "jde_source_watermark_column": "UPMJ",
            "jde_source_watermark_type": "jde_julian_date",
        },
    ),
    "jde_po_header": MigrationTemplateRead(
        template_key="jde_po_header",
        display_name="JDE Purchase Order Header",
        description="Tracks external ora2pg migration for JDE purchase order header data.",
        source_system="JDE Oracle",
        source_type="oracle",
        migration_tool="ora2pg",
        source_schema_suggestion="PRODDTA",
        source_table="F4301",
        target_schema="mdp_staging",
        target_table="stg_jde_po_header",
        primary_key_columns=["po_no"],
        load_mode="external_bulk",
        initial_load_strategy="external_defined",
        incremental_strategy="greater_than_last_watermark",
        watermark_column="updated_at",
        watermark_column_type="datetime",
        lookback_window_days=1,
        validation_level="key_integrity",
        config={
            **_JDE_BASE_CONFIG,
            "ora2pg_project": "jde_po_header",
            "jde_tables": ["F4301"],
            "jde_source_watermark_column": "UPMJ",
            "jde_source_watermark_type": "jde_julian_date",
        },
    ),
    "jde_po_line": MigrationTemplateRead(
        template_key="jde_po_line",
        display_name="JDE Purchase Order Line",
        description="Tracks external ora2pg migration for JDE purchase order detail/line data.",
        source_system="JDE Oracle",
        source_type="oracle",
        migration_tool="ora2pg",
        source_schema_suggestion="PRODDTA",
        source_table="F4311",
        target_schema="mdp_staging",
        target_table="stg_jde_po_line",
        primary_key_columns=["po_no", "line_no"],
        load_mode="external_bulk",
        initial_load_strategy="external_defined",
        incremental_strategy="greater_than_last_watermark",
        watermark_column="updated_at",
        watermark_column_type="datetime",
        lookback_window_days=1,
        validation_level="key_integrity",
        config={
            **_JDE_BASE_CONFIG,
            "ora2pg_project": "jde_po_line",
            "jde_tables": ["F4311"],
            "jde_source_watermark_column": "UPMJ",
            "jde_source_watermark_type": "jde_julian_date",
        },
    ),
    "jde_po_receipt": MigrationTemplateRead(
        template_key="jde_po_receipt",
        display_name="JDE Purchase Order Receipt",
        description="Tracks external ora2pg migration for JDE purchase order receipt/goods receipt data.",
        source_system="JDE Oracle",
        source_type="oracle",
        migration_tool="ora2pg",
        source_schema_suggestion="PRODDTA",
        source_table="F43121",
        target_schema="mdp_staging",
        target_table="stg_jde_po_receipt",
        primary_key_columns=["receipt_no"],
        load_mode="external_bulk",
        initial_load_strategy="external_defined",
        incremental_strategy="greater_than_last_watermark",
        watermark_column="updated_at",
        watermark_column_type="datetime",
        lookback_window_days=1,
        validation_level="key_integrity",
        config={
            **_JDE_BASE_CONFIG,
            "ora2pg_project": "jde_po_receipt",
            "jde_tables": ["F43121"],
            "jde_source_watermark_column": "UPMJ",
            "jde_source_watermark_type": "jde_julian_date",
        },
    ),
    "jde_ap_invoice": MigrationTemplateRead(
        template_key="jde_ap_invoice",
        display_name="JDE AP Invoice",
        description="Tracks external ora2pg migration for JDE accounts payable invoice data.",
        source_system="JDE Oracle",
        source_type="oracle",
        migration_tool="ora2pg",
        source_schema_suggestion="PRODDTA",
        source_table="F0411",
        target_schema="mdp_staging",
        target_table="stg_jde_ap_invoice",
        primary_key_columns=["invoice_no"],
        load_mode="external_bulk",
        initial_load_strategy="external_defined",
        incremental_strategy="greater_than_last_watermark",
        watermark_column="updated_at",
        watermark_column_type="datetime",
        lookback_window_days=1,
        validation_level="key_integrity",
        config={
            **_JDE_BASE_CONFIG,
            "ora2pg_project": "jde_ap_invoice",
            "jde_tables": ["F0411"],
            "jde_source_watermark_column": "UPMJ",
            "jde_source_watermark_type": "jde_julian_date",
        },
    ),
    "jde_purchase_order_summary_view": MigrationTemplateRead(
        template_key="jde_purchase_order_summary_view",
        display_name="JDE Purchase Order Summary View",
        description="Registers the curated PostgreSQL purchase order summary view built from migrated JDE staging tables.",
        template_type="curated_view",
        source_system="PostgreSQL Staging",
        source_type="postgresql",
        migration_tool="manual",
        source_schema_suggestion="mdp_staging",
        source_table="vw_jde_purchase_order_summary",
        target_schema="mdp_staging",
        target_table="vw_jde_purchase_order_summary",
        primary_key_columns=["po_no"],
        load_mode="validation_only",
        initial_load_strategy="external_defined",
        incremental_strategy="none",
        watermark_column=None,
        watermark_column_type=None,
        lookback_window_days=None,
        validation_level="basic",
        config={
            "template_type": "curated_view",
            "depends_on_targets": [
                "mdp_staging.stg_jde_supplier",
                "mdp_staging.stg_jde_po_header",
                "mdp_staging.stg_jde_po_line",
                "mdp_staging.stg_jde_ap_invoice",
            ],
        },
    ),
}


def list_migration_templates() -> list[MigrationTemplateRead]:
    return [deepcopy(template) for template in _TEMPLATES.values()]


def get_migration_template(template_key: str) -> MigrationTemplateRead | None:
    template = _TEMPLATES.get(template_key)
    return deepcopy(template) if template else None


def migration_job_from_template(
    template: MigrationTemplateRead,
    *,
    name: str | None = None,
    source_connection_id: Any | None = None,
    source_schema: str | None = None,
    target_table: str | None = None,
    estimated_rows: int | None = None,
    estimated_size_gb: float | None = None,
    config: dict[str, Any] | None = None,
) -> MigrationJobCreate:
    merged_config = {**(template.config or {})}
    if config:
        merged_config.update(config)

    return MigrationJobCreate(
        name=name or f"migrate_{template.template_key}",
        description=template.description,
        source_system=template.source_system,
        source_connection_id=source_connection_id,
        source_type=template.source_type,
        migration_tool=template.migration_tool,
        source_schema=source_schema or template.source_schema_suggestion,
        source_table=template.source_table,
        target_schema=template.target_schema,
        target_table=target_table or template.target_table,
        estimated_rows=estimated_rows if estimated_rows is not None else template.estimated_rows,
        estimated_size_gb=estimated_size_gb if estimated_size_gb is not None else template.estimated_size_gb,
        primary_key_columns=template.primary_key_columns,
        load_mode=template.load_mode,
        initial_load_strategy=template.initial_load_strategy,
        incremental_strategy=template.incremental_strategy,
        watermark_column=template.watermark_column,
        watermark_column_type=template.watermark_column_type,
        lookback_window_days=template.lookback_window_days,
        validation_level=template.validation_level,
        status="active",
        config=merged_config or None,
    )
